In [1]:
import numpy as np

In [5]:
myArr2d = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9,10,11,12]])

In [ ]:
myArr2d[0]

array([1, 2, 3, 4])

In [6]:
myArr2d[:,2]

array([ 3,  7, 11])

In [20]:
myArr2d[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
myArr2d[:2,2:]

array([[3, 4],
       [7, 8]])

In [27]:
myArr1 = np.array([10, 23, 2, 7, 90, 65, 32, 66, 70])

In [28]:
idx = [1,3,5]

In [29]:
myArr1[idx]

array([23,  7, 65])

In [30]:
myArr2d = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9,10,11,12]])

In [31]:
myArr2d[[0,1], :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
myArr2d[:,[1,2,3]]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [34]:
myArr2 = np.array([1,2,3,4,5,6,7])

In [37]:
myArr2Result = [True, False, True, False, True, False, True] # 참인 값만 출력

In [38]:
myArr2[myArr2Result]

array([1, 3, 5, 7])

In [39]:
myArr2d = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9,10,11,12]])

In [40]:
myArr2d > 2

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [41]:
myArr2d[myArr2d > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [42]:
myArr2d[myArr2d < 5]

array([1, 2, 3, 4])

In [44]:
myList = [1,2,3,4,5,6,7,8,9,10]

In [45]:
myList

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [49]:
myArr3 = np.arange(1,11) # 1에서 시작 부터 11개값

In [50]:
myArr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
myArr4 = np.arange(start = 1, stop = 11)

In [52]:
myArr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
myArr5 = np.arange(11,1)

In [54]:
myArr5

array([], dtype=int32)

In [55]:
myArr6 = np.arange(stop = 11, start= 1)

In [56]:
myArr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
myArr6 = np.arange(1,11,2)

In [59]:
myArr6

array([1, 3, 5, 7, 9])

In [60]:
myArr7 = np.arange(start = 1, stop = 11, step= 2)

In [61]:
myArr7

array([1, 3, 5, 7, 9])

In [62]:
myArr8 = np.arange(1,11)

In [63]:
myArr8

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
for i in myArr8:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [65]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [66]:
for i in range(1,11,2):
    print(i)

1
3
5
7
9


In [67]:
myArr9 = np.array([1,10,5,8,2,4,3,6,8,7,9])

In [68]:
myArr9

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [69]:
np.sort(myArr9)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [72]:
np.sort(myArr9[::-1])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [73]:
np.sort(myArr9)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [74]:
myArr9 # sort 값을 써도 원본값은 바뀌지 않음

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [76]:
myArr9.sort() # 원본 값을 바꿔주는 방법

In [77]:
myArr9

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [78]:
myArr2d = np.array([[5, 6, 7, 8],
                    [4, 2, 3, 1],
                    [10, 9, 12, 11]])

In [79]:
myArr2d.shape

(3, 4)

In [80]:
myArr2d

array([[ 5,  6,  7,  8],
       [ 4,  2,  3,  1],
       [10,  9, 12, 11]])

In [81]:
np.sort(myArr2d, axis=1) # 열 정렬

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [82]:
myArr2d

array([[ 5,  6,  7,  8],
       [ 4,  2,  3,  1],
       [10,  9, 12, 11]])

In [84]:
np.sort(myArr2d, axis=0)

array([[ 4,  2,  3,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])

In [85]:
myArr2d = np.array([[5, 6, 7, 8],
                    [4, 2, 3, 1],
                    [10, 9, 12, 11]])

In [86]:
myArr2d

array([[ 5,  6,  7,  8],
       [ 4,  2,  3,  1],
       [10,  9, 12, 11]])

In [87]:
np.argsort(myArr2d,axis=1)

array([[0, 1, 2, 3],
       [3, 1, 2, 0],
       [1, 0, 3, 2]], dtype=int64)

In [89]:
np.sort(myArr2d,axis=0)

array([[ 4,  2,  3,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])

In [90]:
np.argsort(myArr2d,axis = 0)

array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [2, 2, 2, 2]], dtype=int64)