In [1]:
import numpy

In [2]:
numpy

<module 'numpy' from 'c:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\numpy\\__init__.py'>

In [3]:
 import numpy as np #alias : 긴 단어를 짧게

In [4]:
np

<module 'numpy' from 'c:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\numpy\\__init__.py'>

In [5]:
arr = np.array([1,2,3,4], dtype=int)

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
[1,2,3,4]

[1, 2, 3, 4]

In [9]:
type([1,2,3,4])

list

In [10]:
type(arr)

numpy.ndarray

In [11]:
myList1 = [1,2,3,4]

In [12]:
myArr1=np.array(mylist1)

In [13]:
myArr1.shape # 데이터의 개수(차원)

(4,)

In [15]:
myList2 = [[1,2,3,4],[5,6,7,8]]

In [16]:
myArr2 = np.array(myList2)

In [17]:
myArr2.shape # 2행 4열

(2, 4)

In [18]:
myList3 = [100, 3.14, 'ryan', '1234']

In [19]:
myList3

[100, 3.14, 'ryan', '1234']

In [20]:
myList3[0]

100

In [21]:
myList3[1]

3.14

In [22]:
myList3[2]

'ryan'

In [23]:
myList3[3]

'1234'

In [24]:
myArr4 = np.array([1,2,3,3.14]) # 단일 타입으로 만들어짐

In [25]:
myArr4

array([1.  , 2.  , 3.  , 3.14])

In [26]:
myArr5 = np.array([1,2,3,3.14],dtype=int)

In [27]:
myArr5

array([1, 2, 3, 3])

In [29]:
myArr6 = np.array([100, 3.14, 'ryan', '1234'])

In [30]:
myArr6

array(['100', '3.14', 'ryan', '1234'], dtype='<U32')

In [31]:
myArr6[0] + myArr6[1]

'1003.14'

In [32]:
myArr7 = np.array([100, 3.14, '1234'], dtype=int)

In [33]:
myArr7

array([ 100,    3, 1234])

In [34]:
myArr8 = np.array([0,1,2,3,4,5,6,7,8,9])

In [35]:
myArr8.shape

(10,)

In [36]:
myArr8[0]

0

In [38]:
myArr8[9]

9

In [39]:
myArr8[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [40]:
myArr8[-1] # -는 오른쪽 마지막 값부터 출력

9

In [41]:
myArr8[-10]

0

In [42]:
myArr8[-11]

IndexError: index -11 is out of bounds for axis 0 with size 10

In [45]:
myArr2d = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]]) # 2차원 배열

In [46]:
myArr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
myArr2d.shape

(3, 4)

In [50]:
myArr2d[0][2] # 0행2열의 값을 출력

3

In [51]:
myArr2d[0,2] # 0행2열의 값을 출력

3

In [52]:
myArr2d[2,1]

10

In [57]:
myArr9 = np.array([0,1,2,3,4,5,6,7,8,9])

In [58]:
myArr9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
myArr9[1:] # 1이상

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
myArr9[:5] # 5미만

array([0, 1, 2, 3, 4])

In [62]:
myArr9[1:5]

array([1, 2, 3, 4])

In [63]:
myArr9[0:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])